name: Only Flow
on: 
  push:
    branches:
      - staging

jobs:
  docker-file-job:  
    name: Only one OS
    runs-on: ubuntu-latest
    steps:
    - name: Checking Out the Repo
      id: checking
      uses: actions/checkout@v1
    - name: Change workdir
      run: cd ./src/
    - name: Build DockerFile and use
      id: building
      uses: ../.github/actions/