name: Docker Image CI

on: 
  push:
    branches:
      - staging

jobs:

  build:
    name: Only one OS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: .github/actions/actions.yml
